// GENERATED by scripts/build-playlist.mjs — do not edit by hand.
// Channel lists live in public/playlist/<slug>.json and are fetched on demand.

export interface ChannelCountry {
  slug: string;
  prefix: string;
  iso: string | null;
  name: { fr: string; en: string; de: string };
  count: number;
  groups: number;
}

export const channelCountries: ChannelCountry[] = [
  {
    "slug": "ch",
    "prefix": "CH",
    "iso": "ch",
    "name": {
      "fr": "Suisse",
      "en": "Switzerland",
      "de": "Schweiz"
    },
    "count": 228,
    "groups": 6
  },
  {
    "slug": "de",
    "prefix": "DE",
    "iso": "de",
    "name": {
      "fr": "Allemagne",
      "en": "Germany",
      "de": "Deutschland"
    },
    "count": 2339,
    "groups": 46
  },
  {
    "slug": "at",
    "prefix": "AT",
    "iso": "at",
    "name": {
      "fr": "Autriche",
      "en": "Austria",
      "de": "Österreich"
    },
    "count": 513,
    "groups": 6
  },
  {
    "slug": "fr",
    "prefix": "FR",
    "iso": "fr",
    "name": {
      "fr": "France",
      "en": "France",
      "de": "Frankreich"
    },
    "count": 2313,
    "groups": 31
  },
  {
    "slug": "nl",
    "prefix": "NL",
    "iso": "nl",
    "name": {
      "fr": "Pays-Bas",
      "en": "Netherlands",
      "de": "Niederlande"
    },
    "count": 2370,
    "groups": 34
  },
  {
    "slug": "uk",
    "prefix": "UK",
    "iso": "gb",
    "name": {
      "fr": "Royaume-Uni",
      "en": "United Kingdom",
      "de": "Vereinigtes Königreich"
    },
    "count": 3050,
    "groups": 85
  },
  {
    "slug": "ie",
    "prefix": "IE",
    "iso": "ie",
    "name": {
      "fr": "Irlande",
      "en": "Ireland",
      "de": "Irland"
    },
    "count": 151,
    "groups": 9
  },
  {
    "slug": "be",
    "prefix": "BE",
    "iso": "be",
    "name": {
      "fr": "Belgique",
      "en": "Belgium",
      "de": "Belgien"
    },
    "count": 401,
    "groups": 12
  },
  {
    "slug": "4k",
    "prefix": "4K",
    "iso": null,
    "name": {
      "fr": "4K Ultra HD",
      "en": "4K Ultra HD",
      "de": "4K Ultra HD"
    },
    "count": 26,
    "groups": 1
  },
  {
    "slug": "it",
    "prefix": "IT",
    "iso": "it",
    "name": {
      "fr": "Italie",
      "en": "Italy",
      "de": "Italien"
    },
    "count": 1284,
    "groups": 17
  },
  {
    "slug": "es",
    "prefix": "ES",
    "iso": "es",
    "name": {
      "fr": "Espagne",
      "en": "Spain",
      "de": "Spanien"
    },
    "count": 2417,
    "groups": 51
  },
  {
    "slug": "pt",
    "prefix": "PT",
    "iso": "pt",
    "name": {
      "fr": "Portugal",
      "en": "Portugal",
      "de": "Portugal"
    },
    "count": 776,
    "groups": 13
  },
  {
    "slug": "pl",
    "prefix": "PL",
    "iso": "pl",
    "name": {
      "fr": "Pologne",
      "en": "Poland",
      "de": "Polen"
    },
    "count": 813,
    "groups": 20
  },
  {
    "slug": "gr",
    "prefix": "GR",
    "iso": "gr",
    "name": {
      "fr": "Grèce",
      "en": "Greece",
      "de": "Griechenland"
    },
    "count": 625,
    "groups": 14
  },
  {
    "slug": "cy",
    "prefix": "CY",
    "iso": "cy",
    "name": {
      "fr": "Chypre",
      "en": "Cyprus",
      "de": "Zypern"
    },
    "count": 78,
    "groups": 3
  },
  {
    "slug": "lv",
    "prefix": "LV",
    "iso": "lv",
    "name": {
      "fr": "Lettonie",
      "en": "Latvia",
      "de": "Lettland"
    },
    "count": 30,
    "groups": 1
  },
  {
    "slug": "se",
    "prefix": "SE",
    "iso": "se",
    "name": {
      "fr": "Suède",
      "en": "Sweden",
      "de": "Schweden"
    },
    "count": 2170,
    "groups": 31
  },
  {
    "slug": "dk",
    "prefix": "DK",
    "iso": "dk",
    "name": {
      "fr": "Danemark",
      "en": "Denmark",
      "de": "Dänemark"
    },
    "count": 1052,
    "groups": 16
  },
  {
    "slug": "no",
    "prefix": "NO",
    "iso": "no",
    "name": {
      "fr": "Norvège",
      "en": "Norway",
      "de": "Norwegen"
    },
    "count": 957,
    "groups": 16
  },
  {
    "slug": "fi",
    "prefix": "FI",
    "iso": "fi",
    "name": {
      "fr": "Finlande",
      "en": "Finland",
      "de": "Finnland"
    },
    "count": 588,
    "groups": 9
  },
  {
    "slug": "is",
    "prefix": "IS",
    "iso": "is",
    "name": {
      "fr": "Islande",
      "en": "Iceland",
      "de": "Island"
    },
    "count": 180,
    "groups": 4
  },
  {
    "slug": "hu",
    "prefix": "HU",
    "iso": "hu",
    "name": {
      "fr": "Hongrie",
      "en": "Hungary",
      "de": "Ungarn"
    },
    "count": 203,
    "groups": 2
  },
  {
    "slug": "ro",
    "prefix": "RO",
    "iso": "ro",
    "name": {
      "fr": "Roumanie",
      "en": "Romania",
      "de": "Rumänien"
    },
    "count": 203,
    "groups": 2
  },
  {
    "slug": "al",
    "prefix": "AL",
    "iso": "al",
    "name": {
      "fr": "Albanie",
      "en": "Albania",
      "de": "Albanien"
    },
    "count": 1241,
    "groups": 16
  },
  {
    "slug": "au",
    "prefix": "AU",
    "iso": "au",
    "name": {
      "fr": "Australie",
      "en": "Australia",
      "de": "Australien"
    },
    "count": 355,
    "groups": 8
  },
  {
    "slug": "nz",
    "prefix": "NZ",
    "iso": "nz",
    "name": {
      "fr": "Nouvelle-Zélande",
      "en": "New Zealand",
      "de": "Neuseeland"
    },
    "count": 72,
    "groups": 3
  },
  {
    "slug": "ma",
    "prefix": "MA",
    "iso": "ma",
    "name": {
      "fr": "Maroc",
      "en": "Morocco",
      "de": "Marokko"
    },
    "count": 106,
    "groups": 2
  },
  {
    "slug": "cz",
    "prefix": "CZ",
    "iso": "cz",
    "name": {
      "fr": "Tchéquie",
      "en": "Czechia",
      "de": "Tschechien"
    },
    "count": 440,
    "groups": 4
  },
  {
    "slug": "exyu",
    "prefix": "EXYU",
    "iso": null,
    "name": {
      "fr": "Ex-Yougoslavie",
      "en": "Ex-Yugoslavia",
      "de": "Ex-Jugoslawien"
    },
    "count": 113,
    "groups": 3
  },
  {
    "slug": "sr",
    "prefix": "SR",
    "iso": "rs",
    "name": {
      "fr": "Serbie",
      "en": "Serbia",
      "de": "Serbien"
    },
    "count": 373,
    "groups": 2
  },
  {
    "slug": "bh",
    "prefix": "BH",
    "iso": "ba",
    "name": {
      "fr": "Bosnie-Herzégovine",
      "en": "Bosnia & Herzegovina",
      "de": "Bosnien-Herzegowina"
    },
    "count": 104,
    "groups": 2
  },
  {
    "slug": "hr",
    "prefix": "HR",
    "iso": "hr",
    "name": {
      "fr": "Croatie",
      "en": "Croatia",
      "de": "Kroatien"
    },
    "count": 211,
    "groups": 2
  },
  {
    "slug": "mk",
    "prefix": "MK",
    "iso": "mk",
    "name": {
      "fr": "Macédoine du Nord",
      "en": "North Macedonia",
      "de": "Nordmazedonien"
    },
    "count": 112,
    "groups": 2
  },
  {
    "slug": "si",
    "prefix": "SI",
    "iso": "si",
    "name": {
      "fr": "Slovénie",
      "en": "Slovenia",
      "de": "Slowenien"
    },
    "count": 34,
    "groups": 2
  },
  {
    "slug": "cg",
    "prefix": "CG",
    "iso": "me",
    "name": {
      "fr": "Monténégro",
      "en": "Montenegro",
      "de": "Montenegro"
    },
    "count": 244,
    "groups": 2
  },
  {
    "slug": "bg",
    "prefix": "BG",
    "iso": "bg",
    "name": {
      "fr": "Bulgarie",
      "en": "Bulgaria",
      "de": "Bulgarien"
    },
    "count": 246,
    "groups": 2
  },
  {
    "slug": "tr",
    "prefix": "TR",
    "iso": "tr",
    "name": {
      "fr": "Turquie",
      "en": "Turkey",
      "de": "Türkei"
    },
    "count": 1233,
    "groups": 16
  },
  {
    "slug": "ku",
    "prefix": "KU",
    "iso": null,
    "name": {
      "fr": "Kurde",
      "en": "Kurdish",
      "de": "Kurdisch"
    },
    "count": 303,
    "groups": 7
  },
  {
    "slug": "ca",
    "prefix": "CA",
    "iso": "ca",
    "name": {
      "fr": "Canada",
      "en": "Canada",
      "de": "Kanada"
    },
    "count": 1484,
    "groups": 28
  },
  {
    "slug": "us",
    "prefix": "US",
    "iso": "us",
    "name": {
      "fr": "États-Unis",
      "en": "United States",
      "de": "Vereinigte Staaten"
    },
    "count": 11678,
    "groups": 92
  }
];

export const totalChannels = 41116;
